### ISSUE TITLE
From address rewriting

### ISSUE THREAD

**Issue by bacilko1** [AGWA/batv-tools#5]
Hi Andrew,

first of all, thanks for your activity on this field.

I would like to ask a question regarding your tool. I got it installed and hopefully correctly configured using postfix as MTA.
I checked the mail flow and headers and it seems that your batv tool is rewriting From field instead of Return-Path field.

I am not very skilled in this field, and just compare this behavior to how the MS Exchange Edge change headers. At least for me it looks to be better to just change return-path - or maybe i do something wrong.

Is it possible to lost a word about this for me?

Thanks a lot
Tomas

**Comment by AGWA** [comment]
Hi Tomas,

batv-tools doesn't rewrite the body `From: ` header - it only changes the `Return-Path: `.  (Technically, it changes the envelope sender, which gets turned into the `Return-Path: ` header by the receiving MTA.)

What makes you think it's changing the `From: ` header?

**Comment by bacilko1** [comment]
Hi Andrew,

you are completely right - i do just a very incomplete test of mailflow, using just telnet 25 , to, from, subject data, and the email comes from name+prvs=xxx@domain.com and not from name@domain.com, now i check it using normal mail client and it seems to be correct.

So again sorry for making premature conclusions ... your tool seems to work fine and I will deploy it in our preproduction environment to check it in real world.

Thanks a lot!
Tomas
