### ISSUE TITLE
Why using SMFIS_REJECT instead of SMFIS_DISCARD

### ISSUE THREAD

**Issue by DanielAW** [AGWA/batv-tools#6]
Hi,

is there a reason why you use `SMFIS_REJECT` instead of `SMFIS_DISCARD`? I'm not sure what `SMFIS_REJECT` does. I do not want to generate a reject message for each and every bounce message.

Cheers Daniel

**Comment by AGWA** [comment]
`SMFIS_REJECT` causes the MTA to respond with a permanent SMTP failure.  It doesn't cause any bounce messages to be sent.  I think discarding is generally bad behavior for a mail server, because it leads the sender to think the message was accepted for delivery when it really wasn't.

**Comment by DanielAW** [comment]
Thanks for your quick reply and good explanation :-)
